### ISSUE TITLE
DNN Platform RC2 > Persona Bar > Manage > Site Assets > Icons not displayed on page load in IE11

### ISSUE THREAD

**Issue by DinKumar** [dnnsoftware/Dnn.AdminExperience#430] opened 2019-03-10 08:12 UTC
## Precondition
1. Install latest Platform RC Build
2. Host user credentials are available to access the application

## Description of bug
Views and Actions icons are not displayed on accessing Site Assets page in IE11. When we hover the mouse on these icons then its displayed.

## Steps to reproduce
1. Access DNN Platform application in IE11 browser.
2. Login as host user.
3. Go to Persona Bar > Manage > Site Assets

## Current result
Views and Actions icons are not displayed in IE11.

## Expected result
Views and Actions icons should be loaded and displayed on accessing Site Assets page.

## Screenshots
![Platform-RC2-SiteAssets-Icons-IE11](https://user-images.githubusercontent.com/40901826/54082339-115d4480-433a-11e9-8fde-00706a89d34e.png)

## Error log
Paste the error log that is related to this issue.

## Additional context
Add any other context about the bug that may be helpful for resolution.

## Affected version

* [x] 9.3.0
* [ ] 9.2.2
* [ ] 9.2.1
* [ ] 9.2
* [ ] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [x] Internet Explorer
* [ ] Edge

**Comment by mikebigun** [comment] 2019-03-13 15:52
Dear community,

Investigating this problem we found it is reproducible using following IE11 build:
_Version: 11.407.17134.0
Update Versions: 11.0.95_

Running same DNN instance using newer IE11 build we couldn't see the problem.
_Version: 11.904.16299.0
Update Versions: 11.0.105_

It makes this problem very specific to a particular IE build version and doesn't look like showstopper to include it to 9.3.0. Hope we should be fine to have this fixed in 9.3.1. Validated also in a Chrome and Edge, no issues detected.

![image](https://user-images.githubusercontent.com/22524011/54292515-03682780-45b7-11e9-9167-54a43b898e2f.png)

**Comment by sleupold** [comment] 2019-03-13 15:54
Are the IE versions tied to specific OS versions or does the older one just missing updates?

**Comment by mikebigun** [comment] 2019-03-13 16:04
As per my limited knowledge on this, IE is supplied with a window patch updates. I have a bit newer patch installed comparing to the patch installed on the issue originator machine. Keeping windows OS up to date should resolve this problem.

![image](https://user-images.githubusercontent.com/22524011/54293879-68bd1800-45b9-11e9-8596-7295030d5c64.png)

**Comment by valadas** [comment] 2019-03-15 08:52
I got 11.0.111 on a windows 10 machine and it works fine.
I got 11.0.100 on a windows 2008 R2 working fine too:

![image](https://user-images.githubusercontent.com/6371568/54419536-14f81f00-46de-11e9-880f-409ea34942c7.png)

So I guess with updates even on very old windows versions, this would be a non-issue...

**Comment by valadas** [comment] 2019-03-15 08:57
I have removed this from the 2.0.0 milestone @DinKumar can you check if the problem goes away with a windows update and report back?

**Comment by valadas** [comment] 2019-05-27 03:37
We have no news on this issue since March, I am closing it assuming windows updates fixes this.

**Closed as completed by valadas** 2019-05-27 03:37 UTC
Labels: bug
