### ISSUE TITLE
Cannot Create Module from Manifest

### ISSUE THREAD

**Issue by ohine** [dnnsoftware/Dnn.AdminExperience#16] opened 2018-08-12 14:02 UTC
GetModuleFiles function doesn't retrieve manifest files

Wrong Get: /API/PersonaBar/Extensions/GetModuleFiles?ownerFolder=MyFolder&moduleFolder=SubFolder&type=3

Correct Get: /API/PersonaBar/Extensions/GetModuleFiles?ownerFolder=MyFolder&moduleFolder=SubFolder&type=2

change js function in Admin\Dnn.PersonaBar\Modules\Dnn.Extensions\scripts\bundles\extensions-bundle.js
'onFolderSelect' .... type: 3 to type: 2

![wrong type](https://cloud.githubusercontent.com/assets/13593736/24123084/6fc91fd6-0d7b-11e7-9b5c-af2a65695059.jpg)

Originally created by @ala-musleh at https://github.com/dnnsoftware/Dnn.AdminExperience.Extensions/issues/47

**Comment by ohine** [comment] 2018-08-12 14:03
Comment by @ala-musleh

> Even now after the manifest file showin the dropdown. still cannot create the module (missing manifest error)
> post url: "/en-us/API/PersonaBar/Extensions/CreateModule"

> this is already reported here: https://dnntracker.atlassian.net/browse/DNN-9608

**Comment by valadas** [comment] 2019-03-05 21:15
I have not tested yet, assigning 9.3.1 but recommend testing and adding steps to reproduce before coding anything.

Related resources:
https://www.dnnsoftware.com/forums/forumid/203/threadid/535890/scope/posts
https://dnntracker.atlassian.net/browse/PAE-216

**Comment by valadas** [comment] 2019-03-28 02:31
A PR has been on issue #442 which duplicates this issue, I am closing this one since the other one has a PR on it.

**Closed as completed by valadas** 2019-03-28 02:31 UTC
Labels: bug
