### ISSUE TITLE
DNN Platform RC1 > Persona Bar > Settings > Vocabularies > Console Errors on create new vocabulary

### ISSUE THREAD

**Issue by DinKumar** [dnnsoftware/Dnn.AdminExperience#385] opened 2019-02-05 01:25 UTC
## Precondition
1. Install latest Platform RC1 build 
2. Host user credentials are available

## Description of bug
Application displays console error when user adds new vocabulary. 

## Steps to reproduce
1. Login to DNN Platform as host user 
2. Go to Persona Bar > Settings > Vocabularies 
3. Click on "Create New Vocabulary" 
4. Enter Name, Click on Type as Hierarchy and Click on Create 
5. Refresh the page/ Go to other Tabs 

## Current result
Console error is displayed: 
export-bundle.js?cdv=53:1 Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null 
    at export-bundle.js?cdv=53:1

## Expected result
There should not be any console errors while accessing Vocabularies, create Vocabularies etc. 

## Screenshots
![platform-vocablaries-consoleerror](https://user-images.githubusercontent.com/40901826/52248143-f5b5e700-2912-11e9-9e70-200cebc9c299.png)

## Error log
export-bundle.js?cdv=52:1 Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null
    at export-bundle.js?cdv=52:1

## Additional context
Add any other context about the bug that may be helpful for resolution.

## Affected version

* [x] Platform RC1
* [ ] 9.2.2
* [ ] 9.2.1
* [ ] 9.2
* [ ] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

* [x] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by Mhtshum** [comment] 2019-02-05 09:28
It is related with [#208](https://github.com/dnnsoftware/Dnn.React.Common/issues/208), waiting for PR [#222](https://github.com/dnnsoftware/Dnn.React.Common/issues/222) to be merged

**Comment by Mhtshum** [comment] 2019-02-09 03:56
It changes has been merged and would be fixed in new release [#224](https://github.com/dnnsoftware/Dnn.React.Common/pull/224)

**Comment by valadas** [comment] 2019-02-14 12:23
Cannot reproduce in latest build, closing

**Closed as completed by valadas** 2019-02-14 12:23 UTC
Labels: bug
