### ISSUE TITLE
SEO: Concatenate Page URLs on Off cause a bad url with two ?

### ISSUE THREAD

**Issue by ohine** [dnnsoftware/Dnn.AdminExperience#13] opened 2018-08-12 14:00 UTC
with "Concatenate Page URLs" on _Off_ into SEO settings, when i try to "edit" a module into "Page Setting >Module", the "Module Setting" iframe has an url like (note the double `?`):

    /my-page?moduleid=11585?popup=true&ctl=module&hidecancel=true&hidedelete=true&noredirectonupdate=true
    ________^______________^

the double `?` cause an exception:

> Error: is currently unavailable. DotNetNuke.Services.Exceptions.ModuleLoadException: Formato della stringa di input non corretto. ---> System.FormatException: Formato della stringa di input non corretto. in System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal) in System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info) in DotNetNuke.Modules.Admin.Modules.ModuleSettingsPage.OnInit(EventArgs e)

The problem is in ModuleEdit.js (https://github.com/dnnsoftware/Dnn.AdminExperience.Extensions/blob/2e77c2e19658c90d7cc52c4421a22b26b6c97cf5/src/Modules/Content/Dnn.PersonaBar.Pages/Pages.Web/src/components/Modules/ModuleEdit/ModuleEdit.jsx). This module, into the `render()` method, always concatenate the t`his.props.module.editSettingUrl` with `queryString `, without check if `this.props.module.editSettingUrl` has already a `?` , but `queryString ` already has a `?`:

```js
const queryString = "?popUp=true&HideCancel=true&HideDelete=true&NoRedirectOnUpdate=true";
```

My fix is remove `?` from `queryString ` and add it if necessary into the `render()` method:

```js
const queryString = "popUp=true&HideCancel=true&HideDelete=true&NoRedirectOnUpdate=true";

// ...

render() {
        const {state, props} = this;

        let moduleSettingControlPath = this.props.module.editSettingUrl;
        if( moduleSettingControlPath.indexOf('?') === -1 ){ 
            moduleSettingControlPath += '?';
        } else {
           moduleSettingControlPath += '&';
        }
        moduleSettingControlPath += queryString;
        return (state.userMode === "edit" && 
            <iframe ref="iframe" src={moduleSettingControlPath} style={iFrameStyle} frameBorder={0}></iframe>
        );
    }
```

Originally created by @cesco69

**Comment by valadas** [comment] 2019-01-22 01:22
I cannot reproduce in 9.3.0 RC0 but I will keep this open a bit since I do not think there was any changes done here. @cesco69 can you try out (on a non production environment) if this is fixed for you and if not a few more hints on how to reproduce (which module, what other settings different from defaults, etc.)

**Comment by valadas** [comment] 2019-07-31 07:08
Since there was no reply since january and we could not reproduce, I am closing this issue.

**Closed as completed by valadas** 2019-07-31 07:08 UTC
Labels: question
