### ISSUE TITLE
Bug: Scrolling in dropdown of persona bar fails if screen is not tall enough

### ISSUE THREAD

**Issue by iJungleboy** [dnnsoftware/Dnn.AdminExperience#901] opened 2019-05-01 14:03 UTC
## Description of bug
When using a dropdown - for example to add a language to the portal, a user must scroll through the values. This fails, if the screen is small enough that it has an own scrollbar: 

## Steps to reproduce
List the steps to reproduce the behavior:
1. Resize the screen so it's not extra tall
1. Go to languages, click add
2. open the language picker
3. try to pick any language below the first 5, you simply can't.

## Screenshots
![image](https://user-images.githubusercontent.com/5321186/57020693-66c31d00-6c2a-11e9-93c7-32f8cb9b48d2.png)

## Affected version

* [x] 9.3.2
* [x] 9.3.1

## Affected browser
* [x] Chrome
* [ ] others not tested

**Comment by valadas** [comment] 2019-08-01 00:03
I cannot reproduce in 9.4.0 RC, closing this PR, if you still can reproduce and there are more to it, please comment...

**Closed as completed by valadas** 2019-08-01 00:03 UTC
