### ISSUE TITLE
RFC: UX: Clicking in the area to the right of a PersonaBar editing pane makes it disappear

### ISSUE THREAD

**Issue by OllyHodgson** [dnnsoftware/Dnn.AdminExperience#91] opened 2018-09-27 15:11 UTC
## Description of bug
Often, when in the middle of a task I'll accidentally click outside the PersonaBar. My first thought is usually a four letter expletive. 

Over time I've learnt I can usually pick up where I left off by navigating through the menu again, but when I first used DNN this was _really_ frustating: I thought I'd lost my work.

I also have to write step by step instructions for people to make changes on the system. They're IT support people, who don't know DNN at all. This happens to them all the time - and I have to take the calls to help them get back to where they were.

## Steps to reproduce
1. Open one of the editing panes from the personabar
2. Start work on a multi-step task, such as installing an extension
3. Halfway through, click in the grey area to the right of the editing pane
3. Panic, thinking you've lost your progress

## Current result
The PersonaBar edit pane disappears.

## Expected result
Nothing happens. The PersonaBar edit pane only closes when you click the close icon in the top right.

## Screenshots
Step 4 of 5? Don't accidentally click on the right of the screen:
![image](https://user-images.githubusercontent.com/437224/46155334-f9ec3c80-c26e-11e8-8afe-89d6ca7aec21.png)

Should only close when you click on the close button:
![image](https://user-images.githubusercontent.com/437224/46155438-328c1600-c26f-11e8-8841-fb5fa4c45011.png)

## Affected version

* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [x] 9.1
* [x] 9.0

**Comment by valadas** [comment] 2018-09-27 16:44
I think this is by design. I know for one I rarely use the X and usually just click outside when I am done... Also, no data is lost, if you just click back in the already highlighted menus you get back at the same place with all the data still there...

**Comment by OllyHodgson** [comment] 2018-09-28 09:05
> I think this is by design.

Deisgns can be wrong :wink: 

> Also, no data is lost, if you just click back in the already highlighted menus you get back at the same place with all the data still there...

As experienced DNN users, we know that. I discovered it by accident though - it's not obvious you haven't lost any data. The first few times it happened I swore out loud. 

For me it's far too easy to accidentally make the user interface disappear. I know my experience isn't universal though - other people (like you) might like the way it works.

**Comment by valadas** [comment] 2018-10-01 08:23
Well, in my opinion this is a familiar UI comparable to Windows and Mac notifications panel, they do not even have a close button, you just click outside to dismiss it and if you reopen it you are right back where you where. Same as the start menu as I come to think about it.

That being said, I do not have strong feelings about this, hitting escape is also a quick way to collapse it, so I don't mind if the dismissing behaviour changes on clicking outside.

**Comment by valadas** [comment] 2019-07-31 07:57
In the spirit of cleaning the backlog and since this RFC did not have a strong direction one way or another, I am closing this issue and we can keep the current behavior unless there are multiple persons wanting the opposite...

**Closed as completed by valadas** 2019-07-31 07:57 UTC
Labels: rfc
