### ISSUE TITLE
Persona Bar Error While Trying To Add Tags to Pages Under Page Settings 9.3.1.2

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.AdminExperience#720] opened 2019-04-05 18:01 UTC
## Description of bug
Error while trying to save page tags under page settings persona bar

## Steps to reproduce
List the steps to reproduce the behavior:
1. Go to page settings of a page you created
2. Add new tags to a newly created page
3. Popup message gives error while trying to save

## Current result
Error

## Expected result
Page saves newly added tags

## Screenshots
If applicable, provide screenshots to help explain your problem.

## Error log
 AbsoluteURL /API/PersonaBar/Pages/SavePageDetails DefaultDataProvider DotN 

AbsoluteURL:/API/PersonaBar/Pages/SavePageDetails

DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke

Message:Sequence contains more than one element

StackTrace:

at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source) at Dnn.PersonaBar.Pages.Components.PagesControllerImpl.UpdateTabInfoFromPageSettings(TabInfo tab, PageSettings pageSettings) at Dnn.PersonaBar.Pages.Components.PagesControllerImpl.UpdateTab(TabInfo tab, PageSettings pageSettings) at Dnn.PersonaBar.Pages.Components.PagesControllerImpl.SavePageDetails(PortalSettings settings, PageSettings pageSettings) at Dnn.PersonaBar.Pages.Services.PagesController.SavePageDetails(PageSettings pageSettings) at lambda_method(Closure , Object , Object[] ) at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.b__9(Object instance, Object[] methodParameters) at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Tracing.ITraceWriterExtensions.d__18`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Controllers.ApiControllerActionInvoker.d__0.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Tracing.ITraceWriterExtensions.d__18`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Filters.ActionFilterAttribute.d__5.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Web.Http.Filters.ActionFilterAttribute.d__5.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Filters.ActionFilterAttribute.d__0.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Controllers.ActionFilterResult.d__2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Filters.AuthorizationFilterAttribute.d__2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Controllers.ExceptionFilterResult.d__0.MoveNext()

## Additional context
Had issue creating/saving new pages.  I narrowed it down to this setting causing the bug.

## Affected version

* [x] 9.3.1.2

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by valadas** [comment] 2019-04-13 17:09
I was unable to reproduce this one @thabaum 

Can you test the latest nightly build (not on production site of course) and let us know if you can still reproduce that issue. If so, there must be something a little different on your side that makes the problem happen so can you add some more details to allow us to reproduce it.

Thanks.

**Comment by bryflex** [comment] 2019-05-10 13:15
We encountered this same thing on DNN 9.2. We were able to resolve by visiting the vocabulary groups page and deleted duplicate groups. There was a bunch of tags in the terms table, and there were dups across the portals. It seems to be a multi-portal thing. We believe the duplicate tags/groups might have been introduced via exporting a site template then importing as new portal on same install.  So the bug might be in that process somewhere.

**Comment by valadas** [comment] 2019-07-31 23:56
Since this was not reproducible and it looks like there are some more steps to reproduce, I am closing this issue for now, if you guys come up with an accurate way to reproduce, please open a new issue with those steps.

**Closed as completed by valadas** 2019-07-31 23:56 UTC
Labels: cannot reproduce

**Comment by bryflex** [comment] 2019-08-01 03:17
I was able to duplicate and resolve per my message.

Sent from my iPad

On Jul 31, 2019, at 7:56 PM, Daniel Valadas <notifications@github.com<mailto:notifications@github.com>> wrote:


Since this was not reproducible and it looks like there are some more steps to reproduce, I am closing this issue for now, if you guys come up with an accurate way to reproduce, please open a new issue with those steps.

**Comment by bryflex** [comment] 2019-08-01 11:48
It appears to be a bug with the site export function in DNN. I am not sure if that was resolved yet, but i encountered it on DNN 9.2. To anyone who encounters this, visit the vocabulary groups page and delete any duplicate groups. That resolved it for me.

**Comment by valadas** [comment] 2019-08-01 23:29
@bryflex if you have steps to reproduce and there is a bug with the export/import feature, please do open a new issue with those steps.
